<?php
$title = "My Todo";
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?> </h1>
<p>
    <a href="<?php echo $this->url(
        'todo',
        array('action' => 'add')
    );?>">Add new todo</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Complete</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->paginator as $todo): ?>
        <tr>
            <td><?php echo $this->escapeHtml($todo->getTitle());?></td>
            <td><?php echo $this->escapeHtml($todo->getComplete());?></td>
            <td>
                <a href="<?php echo $this->url(
                    'todo',
                    array(
                        'action' => 'edit',
                        'id'=> $todo->getId()
                    )
                );?>">Edit</a>
                <a href="<?php echo $this->url(
                    'todo',
                    array(
                        'action' => 'delete',
                        'id'=> $todo->getId()
                    )
                );?>">Delete</a>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>

<?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->paginator,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     array('partial/paginator.phtml', 'Album'),
     // the route to link to when a user clicks a control link
     array(
         'route' => 'todo'
     )
 );
